module.exports = {
    random: function() {
        return this.things[ Math.floor( Math.random() * this.things.length ) ];
    },

    things: [
        'Things that are none of your business',
        'Things that confirm you are guilty',
        'Things that tire you out',
        'Things that would get you sent to the Principal\'s office',
        'Things you dream about',
        'Things you shouldn\'t pay any attention to',
        'Things a chicken thinks about when the farmer picks up the eggs',
        'Things a chimp thinks about when he sees you at the zoo',
        'Things a cow thinks about when a farmer milks it',
        'Things a doctor shouldn\'t do while performing surgery',
        'Things a gentleman shouldn\'t do',
        'Things a lady shouldn\'t do',
        'Things a waiter shouldn\'t do',
        'Things about men that frustrate you',
        'Things about women that frustrate you',
        'Things an ideal mate would do for you',
        'Things astronauts complain about in space',
        'Things big dogs think about when they see a Chihuahua',
        'Things cannibals think about while dinning',
        'Things cats think about humans',
        'Things children shouldn\'t know',
        'Things children shouldn\'t play with',
        'Things dogs are actually saying when they bark',
        'Things firemen do between fires',
        'Things fish think about as they swim in their aquarium',
        'Things grown-ups wish they could still do.',
        'Things kids know more about than adults',
        'Things men know more about then women',
        'Things not to do in a hospital',
        'Things not to do while driving!!',
        'Things not to tell your mother',
        'Things paramedics shouldn\'t say to a patient on the way to the hospital',
        'Things people do when no one is looking',
        'Things people do when no one is looking',
        'Things people like about you',
        'Things that are better late than never',
        'Things that are dirty',
        'Things that are embarrassing',
        'Things that are funny',
        'Things that are good!',
        'Things that are harder than they look',
        'Things that are harder than they look',
        'Things that are impossible to measure',
        'Things that are naughty',
        'Things that are politically incorrect',
        'Things that are useless',
        'Things that are wild',
        'Things that are your favorite foods!!',
        'Things that cause an accident',
        'Things that cause trouble',
        'Things that confirm that your life is going downhill',
        'Things that confirm you are losing your memory',
        'Things that confirm you are losing your mind',
        'Things that confirm you have been abducted by aliens',
        'Things that confirm you have had to much to drink',
        'Things that confirm you still haven\'t grown up',
        'Things that confirm your car is a lemon',
        'Things that confirm your house is haunted',
        'Things that confirm your house is haunted!',
        'Things that confirm your life is going downhill',
        'Things that confirm your small town is backward',
        'Things that could get you arrested',
        'Things that could result in a war',
        'Things that could spoil your appetite',
        'Things that could use a good cleaning',
        'Things that don\'t exist but you wish they did',
        'Things that don\'t make sense',
        'Things that dont last very long',
        'Things that drive you mad',
        'Things that exhaust you',
        'Things that give you a headache',
        'Things that go bad',
        'Things that go bad',
        'Things that hang',
        'Things that happen in vegas that should stay in vegas!!',
        'Things that happen once in a blue moon',
        'Things that hurt',
        'Things that hurt your back',
        'Things that jiggle',
        'Things that jiggle',
        'Things that make a good punch line',
        'Things that make ballet more exciting',
        'Things that make people jealous',
        'Things that make sex fun!!!',
        'Things that make you angry',
        'Things that make you cry',
        'Things that make you feel stupid!',
        'Things that make you feel young',
        'Things that make you gag',
        'Things that make you giggle',
        'Things that make you giggle!!!',
        'Things that make you go ahhhh',
        'Things that make you go ooooh',
        'Things that make you jump',
        'Things that make you nervous',
        'Things that make you relax',
        'Things that make you scream',
        'Things that make you uncomfortable',
        'Things that make you uncomfortable',
        'Things that must be magic',
        'Things that must be magic.',
        'Things that prove you\'re in a bad restaurant',
        'Things that really need a referee',
        'Things that require a lot of patience',
        'Things that require an assistant',
        'Things that seem to take an eternity',
        'Things that should come with a manual',
        'Things that should have an expiration date',
        'Things that shouldn\'t be lumpy',
        'Things that shouldn\'t be made into video games!!!',
        'Things that shouldn\'t be passed from one generation to the next',
        'Things that shouldn\'t be passed from one generation to the next',
        'Things that shouldn\'t go into a time capsule',
        'Things that smell terrible',
        'Things that squirt',
        'Things that take courage',
        'Things that usually make you feel better',
        'Things that very old people shouldn\'t do',
        'Things that warrant an apology',
        'Things that would be considered a bad habit',
        'Things that would be fun to do in an elevator',
        'Things that would get a doctor sued for malpractice',
        'Things that would get you discharged from the army',
        'Things that would get you fired',
        'Things that would keep you out of heaven',
        'Things that would make golf more exciting',
        'Things that would make meetings more exciting',
        'Things that would make school more exciting',
        'Things that would make work more exciting',
        'Things that would make your love life more exciting',
        'Things that would probably keep you out of heaven',
        'Things that you can trip over',
        'Things that you can use for transport (car, bike, bus, plane etc)',
        'Things that you love to watch on tv!',
        'Things that you shouldn\'t do in public.',
        'Things that you shouldn\'t swallow.',
        'Things that you shouldn\'t throw off of a building.',
        'Things that you will find in (name room of house..bathroom, kitchen, etc)',
        'Things that your parents would kill you for.',
        'Things there should be an award for',
        'Things to wear to (occasion ...wedding, funeral, etc)',
        'Things women know more about than men',
        'Things women talk about when they go to the restroom together',
        'Things wouldn\'t want to be allergic to',
        'Things you call your mate',
        'Things you can do to get rid of unwanted guests',
        'Things you can never find',
        'Things you can\'t believe someone actually did'
    ]
};
